const fs = require('node:fs');
const path = require('node:path');
const {minify_sync} = require('terser');
const views = {
  'home.js': ['home', false],
  'home-us-turkey.js': ['home', true],
  'mixed.js': ['mixed', false],
  'mixed-us-turkey.js': ['mixed', true],
  'street-reserve.js': ['street', false],
};
// Only local identifiers and formatting change; retain all logic and field names.
const compact = minify_sync(fs.readFileSync(path.join(__dirname, 'naming.js'), 'utf8'), {
  compress: false,
  mangle: true,
  format: {comments: false, ascii_only: false},
}).code;
function output(mode, extra) {
  return '// Generated by build.cjs. Paste this WHOLE file into Shadowrocket Script.\n' +
    'return true;}\n$js_filter_servers=function($servers){return subscriptionNames($servers,' +
    JSON.stringify(mode) + ',' + extra + ')};' + compact +
    '\nfunction $subscription_tail(){\n';
}
if (require.main === module) {
  for (const [file, [mode, extra]] of Object.entries(views)) {
    const target = path.join(__dirname, file), expected = output(mode, extra);
    if (process.argv.includes('--check')) {
      if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8') !== expected) throw Error('Stale generated filter: ' + file);
    } else fs.writeFileSync(target, expected);
  }
  console.log('PASS: five generated filters ' + (process.argv.includes('--check') ? 'current' : 'written'));
}
module.exports = {views, output};
