const fs = require('node:fs');
const path = require('node:path');
const views = {
  'home.js': ['home', false],
  'home-us-turkey.js': ['home', true],
  'mixed.js': ['mixed', false],
  'mixed-us-turkey.js': ['mixed', true],
  'street-reserve.js': ['street', false],
};
function output(mode, extra) {
  return '// Generated by build.cjs. Paste this WHOLE file into Shadowrocket Script.\n' +
    '// Native $server wrapper adapter, verified with Shadowrocket 2.2.92 (3445).\n' +
    'return true;\n}\n$js_filter_servers = function ($servers) {\n' +
    '  return subscriptionNames($servers, ' + JSON.stringify(mode) + ', ' + extra + ');\n};\n' +
    fs.readFileSync(path.join(__dirname, 'naming.js'), 'utf8') +
    '\n// The native wrapper supplies the closing body; this is not a Node script.\n' +
    'function $subscription_tail() {\n';
}
if (require.main === module) {
  for (const [file, [mode, extra]] of Object.entries(views)) {
    const target = path.join(__dirname, file), expected = output(mode, extra);
    if (process.argv.includes('--check')) {
      if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8') !== expected) throw Error('Stale generated filter: ' + file);
    } else fs.writeFileSync(target, expected);
  }
  console.log('PASS: five generated filters ' + (process.argv.includes('--check') ? 'current' : 'written'));
}
module.exports = {views, output};
